#!/usr/bin/env python

import argparse
from tistools import *
import os
import glob


ACCFLAGS, REJFLAGS = set_flags_ACC_REJ()

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Remove all trajectories from non-shooting moves, i.e. remove all non-unique trajectories')
    parser.add_argument("-i", dest="inputfile", default="./retis.rst",
            help="inputfile is file retis.rst or out.rst, where also the 000/ 001/ ... folders are stored",)
    parser.add_argument("-o",dest="outputfile", default="removehistory", 
            help="outputfile is where a description of removed files is kept")


    args = parser.parse_args()
    indir, filename = os.path.split(args.inputfile)

    if len(indir) ==0: indir = "./"
    print("indir:",indir)
    print("filename:",filename)

    print("folders")
    folders = glob.glob(indir+"/0[0-9][0-9]") #element of list folders: "./001"
    folders = sorted(folders)
    for fol in folders:
        print(fol)
    assert len(folders)>0
    
    remove_dirs = []
    for fol in folders:
        toremove_list = list_nonshoot_trajectories(fol)
        remove_dirs+=toremove_list

    with open("removedirs.txt", "w+") as f:
        for el in remove_dirs:
            f.write(str(el)+"\n")
    f.close()

    remove_nonshoot_trajectories(remove_dirs,stop_on_error=False,donotremove=True)
